[package]
name = "standup"
version = "0.0.1"
edition = "2021"
authors = ["Glen Henri J. De Cauwsemaecker"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
